# Generated by Django 4.2.1 on 2023-08-16 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0003_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=250)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='img1',
        ),
        migrations.AddField(
            model_name='team',
            name='phno1',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
