# Generated by Django 4.2.1 on 2023-08-16 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0004_services_remove_team_img1_team_phno1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='desc',
        ),
    ]
