# Generated by Django 4.2.1 on 2023-08-16 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0005_remove_services_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='img1',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='pics1'),
            preserve_default=False,
        ),
    ]
